services:
  server:
    image: node:24-alpine
    container_name: nodeContainer
    user: "node"
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      CHOKIDAR_USEPOLLING: "true" #
    volumes:
      - .:/usr/src/app
    networks:
      - nodeNetwork

networks:
  nodeNetwork:
    driver: bridge
