services:
  server:
    image: node:24-alpine
    container_name: nodeContainer
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/docker/setupEnvironment.sh 
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nodeNetwork

  db:
    image: mongo:6.0
    container_name: mongoContainer
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongoData:/data/db
    networks:
      - nodeNetwork
    healthcheck:
      test: ["CMD-SHELL", "mongosh --user ${DB_USER} --password ${DB_PASSWORD} --eval 'db.runCommand({ping:1})' --quiet"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  nodeNetwork:
    driver: bridge

volumes:
  mongoData:
